AB.Presentation.MVC/Areas/Admin/Pages/ArticleCategoryManagement/Add.cshtml.cs
using AB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AB.Presentation.MVC.Areas.Admin.Pages.ArticleCategoryManagement
{
    public class AddModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public AddModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
        }

        public RedirectToPageResult OnPost(CreateArticleCategory command)
        {
            _articleCategoryApplication.Create(command);
            return RedirectToPage("List");
        }
    }
}

AB.Presentation.MVC/Areas/Admin/Pages/ArticleCategoryManagement/Edit.cshtml.cs
using AB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AB.Presentation.MVC.Areas.Admin.Pages.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public RenameArticleCategory ArticleCategory { get; set; }

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            ArticleCategory = _articleCategoryApplication.Get(id);
        }

        public RedirectToPageResult OnPost()
        {
            _articleCategoryApplication.Rename(ArticleCategory);
            return RedirectToPage("List");
        }
    }
}

AB.Presentation.MVC/Areas/Admin/Pages/ArticleCategoryManagement/List.cshtml.cs
using System.Collections.Generic;
using AB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AB.Presentation.MVC.Areas.Admin.Pages.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategoryViewModels { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategoryViewModels = _articleCategoryApplication.List();
        }

        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleCategoryApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

AB.Presentation.MVC/Areas/Admin/Pages/ArticleManagement/List.cshtml.cs
using System.Collections.Generic;
using AB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AB.Presentation.MVC.Areas.Admin.Pages.ArticleManagement
{
    public class ListModel : PageModel
    {
        [BindProperty]
        public List<ArticleViewModel> Articles { get; set; }

        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.List();
        }
    }
}

AB.Presentation.MVC/Areas/Admin/Pages/ArticleCategoryManagement/Add.cshtml
@page
@model AB.Presentation.MVC.Areas.Admin.Pages.ArticleCategoryManagement.AddModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Create New Article Category</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Title" class="control-label">Title:</label>
                            <input name="Title" id="Title" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a class="btn btn-dark" asp-page="./List" asp-area="Admin">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AB.Presentation.MVC/Areas/Admin/Pages/ArticleCategoryManagement/Edit.cshtml
@page
@model AB.Presentation.MVC.Areas.Admin.Pages.ArticleCategoryManagement.EditModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Edit Article Category: @Model.ArticleCategory.Title</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ArticleCategory.Id" />
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="ArticleCategory.Title" class="control-label">Title:</label>
                            <input asp-for="ArticleCategory.Title" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-warning" />
                        <a class="btn btn-dark" asp-page="./List" asp-area="Admin">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AB.Presentation.MVC/Areas/Admin/Pages/ArticleCategoryManagement/List.cshtml
@page
@model AB.Presentation.MVC.Areas.Admin.Pages.ArticleCategoryManagement.ListModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article Category List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-page="./Add" asp-area="Admin">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>CreationDate</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var articleCategory in Model.ArticleCategoryViewModels)
                {
                    <tr>
                        <td>@articleCategory.Id</td>
                        <td>@articleCategory.Title</td>
                        <td>
                            @if (articleCategory.IsDeleted)
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check fa-2x text-success"></i>
                            }
                        </td>
                        <td>@articleCategory.CreationDate</td>
                        <td>
                            <a class="btn btn-warning float-left mr-3" asp-page="./Edit" asp-route-id="@articleCategory.Id">Rename</a>
                            @if (articleCategory.IsDeleted)
                            {
                                <form method="post" asp-page-handler="Activate" class="float-left">
                                    <button class="btn btn-success">Activate</button>
                                    <input type="hidden" name="id" value="@articleCategory.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="Remove" class="float-left">
                                    <button class="btn btn-danger">Remove</button>
                                    <input type="hidden" name="id" value="@articleCategory.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

AB.Presentation.MVC/Areas/Admin/Pages/ArticleManagement/List.cshtml
@page
@model AB.Presentation.MVC.Areas.Admin.Pages.ArticleManagement.ListModel
@{
}


<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article Category List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-page="./Add" asp-area="Admin">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Article Category</th>
                    <th>Status</th>
                    <th>CreationDate</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var article in Model.Articles)
                {
                    <tr>
                        <td>@article.Id</td>
                        <td>@article.Title</td>
                        <td>@article.ArticleCategory</td>
                        <td>
                            @if (article.IsDeleted)
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check fa-2x text-success"></i>
                            }
                        </td>
                        <td>@article.CreationDate</td>
                        <td>
                            <a class="btn btn-warning float-left mr-3" asp-page="./Edit" asp-route-id="@article.Id">Edit</a>
                            @if (article.IsDeleted)
                            {
                                <form method="post" asp-page-handler="Activate" class="float-left">
                                    <button class="btn btn-success">Activate</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="Remove" class="float-left">
                                    <button class="btn btn-danger">Remove</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

AB.Presentation.MVC/Areas/Admin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Onion.Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Onion.Presentation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-page="/ArticleCategoryManagement/List">ArticleCategoryManagement</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-page="/ArticleManagement/List">ArticleManagement</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-page="/CommentManagement/List">CommentManagement</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light btn btn-info" asp-area="" asp-page="/Index">Visit Site</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Onion.Presentation - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AB.Presentation.MVC/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="~/css/fontastic.css">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="~/vendor/fancyapps/fancybox/jquery.fancybox.min.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/favicon.png">
</head>
<body>
    <header class="header">
        <!-- Main Navbar-->
        <nav class="navbar navbar-expand-lg">
            <div class="search-area">
                <div class="search-area-inner d-flex align-items-center justify-content-center">
                    <div class="close-btn">
                        <i class="icon-close"></i>
                    </div>
                    <div class="row d-flex justify-content-center">
                        <div class="col-md-8">
                            <form action="#">
                                <div class="form-group">
                                    <input type="search" name="search" id="search" placeholder="What are you looking for?">
                                    <button type="submit" class="submit">
                                        <i class="icon-search-1"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <!-- Navbar Brand -->
                <div class="navbar-header d-flex align-items-center justify-content-between">
                    <!-- Navbar Brand -->
                    <a asp-page="/Index"  class="navbar-brand">Master Blogger</a>
                    <!-- Toggle Button-->
                    <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse"
                            aria-expanded="false" aria-label="Toggle navigation"
                            class="navbar-toggler">
                        <span></span><span></span><span></span>
                    </button>
                </div>
                <!-- Navbar Menu -->
                <div id="navbarcollapse" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-page="/Index" class="nav-link ">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-page="/Index" class="nav-link ">Administrator Dashboard</a>
                        </li>
                    </ul>
                    <div class="navbar-text">
                        <a href="#" class="search-btn">
                            <i class="icon-search-1"></i>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="row">
            @RenderBody()
        </div>
    </div>

<footer class="main-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="logo">
                    <h6 class="text-white">Master Blogger</h6>
                </div>
                <div class="contact-details">
                    <p>53 Broadway, Broklyn, NY 11249</p>
                    <p>Phone: (020) 123 456 789</p>
                    <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
                    <ul class="social-menu">
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-behance"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-pinterest"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="menus d-flex">
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">My Account</a>
                        </li>
                        <li>
                            <a href="#">Add Listing</a>
                        </li>
                        <li>
                            <a href="#">Pricing</a>
                        </li>
                        <li>
                            <a href="#">Privacy &amp; Policy</a>
                        </li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">Our Partners</a>
                        </li>
                        <li>
                            <a href="#">FAQ</a>
                        </li>
                        <li>
                            <a href="#">How It Works</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="latest-posts">
                    <a href="#">
                        <div class="post d-flex align-items-center">
                            <div class="image">
                                <img src="~/img/small-thumbnail-1.jpg" alt="..." class="img-fluid">
                            </div>
                            <div class="title">
                                <strong>Hotels for all budgets</strong>
                                <span class="date last-meta">
                                    October 26,
                                    2016
                                </span>
                            </div>
                        </div>
                    </a>
                    <a href="#">
                        <div class="post d-flex align-items-center">
                            <div class="image">
                                <img src="~/img/small-thumbnail-2.jpg" alt="..." class="img-fluid">
                            </div>
                            <div class="title">
                                <strong>Great street atrs in London</strong>
                                <span class="date last-meta">
                                    October 26,
                                    2016
                                </span>
                            </div>
                        </div>
                    </a>
                    <a href="#">
                        <div class="post d-flex align-items-center">
                            <div class="image">
                                <img src="~/img/small-thumbnail-3.jpg" alt="..." class="img-fluid">
                            </div>
                            <div class="title">
                                <strong>Best coffee shops in Sydney</strong>
                                <span class="date last-meta">
                                    October 26,
                                    2016
                                </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="copyrights">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2017. All rights reserved. Your great site.</p>
                </div>
                <div class="col-md-6 text-right">
                    <p>
                        Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/popper.js/umd/popper.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="~/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="~/vendor/fancyapps/fancybox/jquery.fancybox.min.js"></script>
<script src="~/js/front.js"></script>

</body>
</html>